### ISSUE TITLE
UISI mitigation (uhoreg's issues)

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-meta#314]
- [ ] tell other devices when you purposely don't send them keys
  - [x] MSC. PR: https://github.com/matrix-org/matrix-doc/pull/2399
  - [x] js-sdk impl. issue: https://github.com/vector-im/riot-web/issues/3831 PR: https://github.com/matrix-org/matrix-js-sdk/pull/1135
  - [ ] demo
- [x] report on olm errors. PR: https://github.com/matrix-org/matrix-js-sdk/pull/1146
- [x] report on messages sent before you joined a room. issue: https://github.com/vector-im/riot-web/issues/5642 PR: https://github.com/matrix-org/matrix-react-sdk/pull/3881
- [ ] revamp display of UISIs
  - [x] planning doc
  - [x] js-sdk
  - [ ] react-sdk
- [ ] key share requests side of MSC2399
  - [ ] send info
  - [ ] receive/store info
- [ ] report on messages sent before your device logged in. issue: https://github.com/vector-im/riot-web/issues/2258
- [ ] keyshare request feedback from server
  - [ ] MSC
  - [ ] js-sdk impl
- [ ] ...
