### ISSUE TITLE
UI for select a connected network in Room Directory

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-meta#42]
We need an input box to select a connected or bridged network. As per https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=57cea87c78329bc82ced35e9

This will filter the RoomDirectory contents to show only rooms from that network.

---
Linking for reference:
- [x] vector-im/riot-web#2178
- [x] vector-im/riot-ios#717
- [x] vector-im/riot-android#622

**Comment by jeangb** [comment]
### - iOS: 

1. When connected to a non federated home server, open the select directory page. 
Unlike riot-web and riot-android, only the custom hs IP address is displayed instead of his name.

2. Connected to matrix.org, open the select directory page.
Hit + button to add a fake directory: "bla.org". 
An **Internal server error** dialog appears. On android I have "The server may be unaivalable or overloaded"

### - Android: 

1. When connected to a non federated home server, open the select directory page.
Select your custom server. A toast "Internal server error" is displayed.

2. When connected to a non federated home server, open the select directory page.
Your custom server item has an icon **[m]**, the same that **Matrix**, unlike riot-web and riot-ios.

3. When connected to a non federated home server, open the select directory page.
I don't know if that really matters, but order of the room directories is different from riot-web and riot-ios. On Android I have **matrix.org | Matrix | jeangb.org** and **jeangb.org | Matrix | matrix.org** on the others?

**Comment by manuroe** [comment]
@jeangb concerning your iOS remarks:
> When connected to a non federated home server, open the select directory page.
Unlike riot-web and riot-android, only the custom hs IP address is displayed instead of his name.

is the domain used for your hs address in your tests is a true public domain? If not, then this is not a true real life case.

> Connected to matrix.org, open the select directory page.
Hit + button to add a fake directory: "bla.org".
An Internal server error dialog appears. On android I have "The server may be unaivalable or overloaded"

"Internal server error" is a string sent by the home server. Web displays it as well: ![](https://matrix.org/_matrix/media/v1/download/matrix.org/UNUegyvSlarxACmrwIpmghba)

**Comment by jeangb** [comment]
@manuroe 

> @jeangb concerning your iOS remarks:
> > When connected to a non federated home server, open the select directory page.
> Unlike riot-web and riot-android, only the custom hs IP address is displayed instead of his name.
> 
> is the domain used for your hs address in your tests is a true public domain? If not, then this is not a true real life case.
It's not a public name indeed. I don't know, it could be a real life case. Android is able to display the hs name.
