### ISSUE TITLE
Extend MSISDN Verification

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-meta#61]
This story represents the efforts to maximise the coverage of MSISDN verification.

I'm going to track the individual steps on Riot Web for now (even though this is actually a Sydent issue).

### Tasks:
- [ ] Use VMNs where appropriate https://github.com/vector-im/riot-web/issues/3616
- [ ] Use the US long codes for US/Canada https://github.com/vector-im/riot-web/issues/3617
- [ ] Investigate remaining countries
